spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/dellphoto/OneDrive/Documentos/Desarrollo/UNIVERSIDAD/PDS/TallerPDS/V2/config/33.configdata
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000
